### ISSUE TITLE
Add feature-flags to `grill-test-builder`

### ISSUE THREAD

**Issue by chanced** [chanced/grill#5]
for toml:
```toml
[feature-flags]
fancy-regex = ["**/optional/*/ecmascript-regex.json"]
```
for the logic: 
- collect results into a map of paths to a list of applicable feature-flags (`HashMap<Utf8PathBuf, Vec<String>>`)
- add feature flag for each match, for multiple matches use `and`.
- edit `tests/Cargo.toml` and add feature flag if not present, set to empty.
